service: todo-proj-backend 


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

  #below we're defining the function we want to deploy
functions:
  tasks:      #function name
    handler: handler.tasks   #handler name should be = js file name .function(in this case tasks, which is what we've exported)
    events:
      - http:
          path: tasks       #when someone sends a get request, trigger the tasks function
          method: get
          cors: true     #cross origin resource sharing (can this API be used from anywhere)
      - http:
          path: tasks/{taskID}
          method: put
          cors: true     
      - http:
          path: tasks       
          method: post
          cors: true     
      - http:
          path: tasks/{taskID}     
          method: delete
          cors: true     
